services:
  redis:
    image: redis:alpine
    container_name: finsage-cache
    restart: unless-stopped
    expose:
      - 6379
    environment:
      - REDIS_PORT=6379
    networks:
      - finsage-network

  db:
    image: postgres:alpine
    container_name: finsage-db
    restart: unless-stopped
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - finsage-network

  finsage-api:
    image: test/finsage-api:latest
    container_name: finsage-api
    restart: unless-stopped
    depends_on:
      - redis
      - db
    expose:
      - 8080
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    ports:
      - 8080:8080
    networks:
      - finsage-network

networks:
  finsage-network: