name: Test Build and Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest

    services:
      stock:
        image: devfinwiz24/fin-maestro-kin:latest
        ports:
          - 8000:8000


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw + Copy env
        run: |
            chmod +x ./mvnw
            cp .env.example .env

      - name: Run integration tests
        run: ./mvnw verify

  build-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dgclasher/finsage-api:latest